### ISSUE TITLE
Cancelling a building does not refund money.

### ISSUE THREAD

**Issue by adityaravishankar** [adityaravishankar/command-and-conquer#15]

**Comment by Korlus** [comment]
To elaborate, I have experienced this also, and it's not just a building, but when building anything - including units.

**Comment by adityaravishankar** [comment]
How did the original game behave? Full refund or 50% refund?

**Comment by joeyw** [comment]
Full refund for canceled builds.

**Comment by adityaravishankar** [comment]
Ok... Its a quick patch... I just had so much to do, I let this one
slide... Should be fixed on the next update....

**Comment by adityaravishankar** [comment]
Canceling now gives full refund. Should be out in next release
