### ISSUE TITLE
sound went off

### ISSUE THREAD

**Issue by ghost** [adityaravishankar/command-and-conquer#2]
Don't know exactly why.
I have just destroyed the first tank, built an energy plant and commited to an advanced energy plant - when the sound just went off and never came back.

**Comment by adityaravishankar** [comment]
What browser are you using? 

There is a known bug in Chrome that causes sound to fail. It has just been patched a couple of days ago... http://code.google.com/p/chromium/issues/detail?id=107933

**Comment by ghost** [comment]
It's Chrome 16.0.912.75 m

**Comment by adityaravishankar** [comment]
Will have to wait for the Chrome patch to be released to confirm this has been resolved. Do you have similar issues in Firefox/IE9?

**Comment by CosmicBagel** [comment]
No music right from the start, after a short while while sound effects stopped as well.
Windows 7 64bit, NVidia 460GTX, 16.0.912.75 m

**Comment by adityaravishankar** [comment]
I only put the music in the demo not in the main game.... Is this problem
only on Chrome or Firefox/IE9 as well?

The chrome bug has been documented

**Comment by CosmicBagel** [comment]
Firefox 5.0 has no sound, on top of terrible frame lag and showing the turret sprite for many things :P
Firefox 9.0.1 had no sound, but all that other stuff ran nicely (tried reloading a couple times but no good)
IE 9.0.8112.16421 Never loaded, waited for over an hour

Windows 7 x64 NVidia 460 GTX

Off topic but Chrome the best frame rate

**Comment by black-snow** [comment]
FF 9.0.1 Win7 no sound at all

On Chrome sound chrashed after I selected a light tank and deselected it before the sound was over.

/edit: sound is just fine with FF using local copy - maybe there was an error fetching the sound files in the web version

**Comment by adityaravishankar** [comment]
Seems most errors are due to chrome bug or browser not downloading files.... Closing for now
