### ISSUE TITLE
Building should be able to be started even if user does not have 100% of the money; they just wait when money reaches 0.

### ISSUE THREAD

**Issue by adityaravishankar** [adityaravishankar/command-and-conquer#22]

**Comment by adityaravishankar** [comment]
Daniel Bart Usch : if starting a refinery with 200 credits and right away after a harvester the money goes into negative instead of stopping at 0. and as much as i remember the original c&c you could always start to build something even if there is not enough money. the message "insufficent funds" comes when the money reaches 0

**Comment by black-snow** [comment]
One right-click would stop the building process. A right-click on a stopped building process (buldings as well as units) aborted the process while adding the funds which were already spent on the process.

**Comment by adityaravishankar** [comment]
No more negative. Unit/Building stops building at 0 cash and announces insufficient funds. Can start building even when cash is 0
