### ISSUE TITLE
Most of the map is black

### ISSUE THREAD

**Issue by boyleRecorder** [adityaravishankar/command-and-conquer#23]
Approx 90% of the map is black for me. The top 10% works properly, but below a line the map becomes black and stays black.
- Moving tanks/harvesters over it doesn't reveal the map.
- Creating a building, reveals the immediate area.

**Comment by adityaravishankar** [comment]
Can you share a screenshot? And the browser/OS?

**Comment by boyleRecorder** [comment]
Browser: Firefox 9.0.1
OS: Windows 7

Screenshot: http://i.imgur.com/qw6Wn.png

**Comment by boyleRecorder** [comment]
Oops closed by accident.

**Comment by adityaravishankar** [comment]
Could you try opening the image /projects/games/command-and-conquer/images/maps/gdi/map01.jpeg in a separate browser window? Maybe the map file didn't load correctly the first time.

**Comment by adityaravishankar** [comment]
Cannot replicate.... Need more feedback... Closing for now
