### ISSUE TITLE
Cursor occasionally disappears when placing building

### ISSUE THREAD

**Issue by mattheyan** [adityaravishankar/command-and-conquer#48]
I'm not sure what causes this, but sometimes when placing a building the cursor is not visible when mousing over the playing area.  Right-click to cancel the action seems to resolve the issue (at least in one case).

**Comment by adityaravishankar** [comment]
Can you give any steps for replicating the issue?

**Comment by mattheyan** [comment]
Was not able to reproduce today, though it happened several times yesterday. I suspect it may have been a browser and/or system performance problem.
