### ISSUE TITLE
Vehicles stuck on non-accessible terrain

### ISSUE THREAD

**Issue by cincauhangus** [adityaravishankar/command-and-conquer#54]
![vehicles stuck in non-accessible terrain](http://a8.sphotos.ak.fbcdn.net/hphotos-ak-ash4/430913_10151228021795176_841385175_22971230_823609280_n.jpg)

**Comment by adityaravishankar** [comment]
Duplicate of the first bug ever...
https://github.com/adityaravishankar/command-and-conquer/issues/1https://github.com/adityaravishankar/command-and-conquer/issues/54
