### ISSUE TITLE
Harvester should automatically find the nearest ore when built

### ISSUE THREAD

**Issue by cincauhangus** [adityaravishankar/command-and-conquer#55]
The harvester should automatically find the nearest ore patch when the vehicle is built. 
Harvester should also go back to the refinery whenever ore has been depleted. it should also go back to the ore patch and wait for ore to regenerate. ore collection should be automated entirely.

**Comment by adityaravishankar** [comment]
As far as I remember, the original game did not do this for newly constructed harvesters. New harvesters would wait to be deployed.... Harvesters from refineries would auto harvest. Can someone confirm?

**Comment by black-snow** [comment]
Separately built harvesters would not go harvesting on their own. Those who come with new refineries will, though, as there is tiberium within the revealed map area.
I don't think harvesters waited for ores to regenerate but will drive back to their last harvesting spot when there is no tiberium within sight (revealed map). They didn't go back to work as soon as it regrew.
Need to check this, though.

**Comment by black-snow** [comment]
Okay I've just checked on this issue.
Just as I said, freshly built harvesters from weapon factory do not start seeking for tiberium on their own. Though, harvesters that are sent to the refinery will start harvesting automatically after they have unloaded (and even if they were empty).

**Comment by cincauhangus** [comment]
Ah, I might have gotten confused with another version of C&C. But I'm sure a harvester will always go back to the refinery even if it's not filled or empty whenever an ore patch is depleted. 

I have a question though, will the harvester search the visible map for any new ore deposits or will it just wait at the refinery?

**Comment by black-snow** [comment]
The harvester will keep on harvesting as long as it can reach any visible ressources. But once it has stopped it wont continue harvesting on its own as ressources regrow. Hence you will need to command it to do so.
