### ISSUE TITLE
freezed unit

### ISSUE THREAD

**Issue by secnir** [adityaravishankar/command-and-conquer#68]
hi
first time: the idea (C&C inside browser) is great!

second time: when i played, a tank unit try move across the hills, and freezed. Later cannot move, only shot to enemies.
If you wish i can send a picture where freezed.

good work to C&C !

**Comment by adityaravishankar** [comment]
Thank you....

Tracking this bug....

Am currently rewriting the entire engine from scratch, so we should be able
to fix this.

https://github.com/adityaravishankar/command-and-conquer/issues/1
