### ISSUE TITLE
In lieu of saving, can we just skip level?

### ISSUE THREAD

**Issue by colinnelson** [adityaravishankar/command-and-conquer#75]

**Comment by adityaravishankar** [comment]
> I'll be adding a load level feature that will let you start after the last
> completed level in a campaign....

Right now, I just want to finish multiplayer beta and bug fixing and
release it to the public....

**Comment by colinnelson** [comment]
Awesome man. This rules!

On Thu, May 24, 2012 at 1:27 PM, Aditya Ravi Shankar <
reply@reply.github.com

**Comment by quantuminformation** [comment]
good issue!
